[package]
name = "report_overdue_charges"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = {version="1.0.140"}
tokio = {version="1.44.2", features=["full"]}
dotenv="0.15.0"